### ISSUE TITLE
Complete remaining components of Beaker API

### ISSUE THREAD

**Issue by epwalsh** [allenai/beaker-py#51]
## Datasets

- [x] `beaker.dataset.ls` (52952ab)
- [x] `beaker.dataset.rename` (2a4aebd)
- [x] `beaker.dataset.size` (a1e765b)
- [x] `beaker.dataset.stream_file` (af423e6)
- [x] `beaker.dataset.sync` (b07b5c8)

## Experiments

- [x] `beaker.experiment.delete`
- [x] `beaker.experiment.rename` (#58)
- [x] `beaker.experiment.results` (#59)
- [x] `beaker.experiment.resume` (2cb9f6a)
- [x] `beaker.experiment.spec` (#59)
- [x] `beaker.experiment.stop` (3eec1bb)
- [x] `beaker.experiment.tasks` (#59)

## Jobs

- [x] `beaker.job.get` (#55)
- [x] `beaker.job.finalize` (#70)
- [x] `beaker.job.list` (#55)
- [x] `beaker.job.results` (d9f267a)
- [x] `beaker.job.stop` (#70)

## Workspaces

- [x] `beaker.workspace.archive` (#71)
- [x] `beaker.workspace.datasets` (#60)
- [x] `beaker.workspace.experiments` (#60)
- [x] `beaker.workspace.images` (#60)
- [x] `beaker.workspace.secrets` (#61)
- [x] `beaker.workspace.list` (#60)
- [x] `beaker.workspace.move` (#71)
- [x] `beaker.workspace.permissions` (#73)
- [x] `beaker.workspace.rename` (#71)
- [x] `beaker.workspace.unarchive` (#71)

## Nodes

- [x] `beaker.node.get` (#55)

## Secrets

Added in #61

- [x] `beaker.secret.read`
- [x] `beaker.secret.write`
- [x] `beaker.secret.delete`

## Groups

Added in #76 

- [x] `beaker.group.add_experiments`
- [x] `beaker.group.create`
- [x] `beaker.group.delete`
- [x] `beaker.group.list_experiments`
- [x] `beaker.group.get`
- [x] `beaker.group.remove_experiments`
- [x] `beaker.group.rename`
